name: Build Eleventy Blog

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm

            - name: Install dependencies & build
              run: |
                  npm ci
                  npm run lint
                  npm run build

            - name: Deploy (if main)
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  publish_dir: ./_site
                  github_token: ${{ secrets.GITHUB_TOKEN }}
